spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ugg_express?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

python:
  command: python3
  script-path: python/parse_payslip.py